# Generated by Django 5.0.1 on 2024-10-30 12:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('activity_type', models.CharField(choices=[('tour', 'Guided Tour'), ('adventure', 'Adventure Activity'), ('workshop', 'Workshop/Class'), ('attraction', 'Attraction Visit'), ('experience', 'Local Experience'), ('water', 'Water Activity'), ('cultural', 'Cultural Activity'), ('food', 'Food & Drinks')], max_length=20)),
                ('languages', models.JSONField(default=list, help_text='List of languages available')),
                ('location_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('meeting_point_details', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('highlights', models.JSONField(default=list)),
                ('included', models.JSONField(default=list)),
                ('not_included', models.JSONField(default=list)),
                ('requirements', models.JSONField(default=list)),
                ('accessibility_info', models.TextField(blank=True)),
                ('duration', models.DurationField(help_text='Duration in hours and minutes')),
                ('skip_the_line', models.BooleanField(default=False)),
                ('instant_confirmation', models.BooleanField(default=True)),
                ('min_participants', models.PositiveIntegerField(default=1)),
                ('max_participants', models.PositiveIntegerField()),
                ('private_available', models.BooleanField(default=False)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('child_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('private_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cancellation_policy', models.TextField()),
                ('booking_deadline_hours', models.PositiveIntegerField(default=24)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activity_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('alt_text', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='activity.activity')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('visit_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('helpful_votes', models.PositiveIntegerField(default=0)),
                ('verified_booking', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='activity.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('available_days', models.JSONField(help_text='List of available days (0-6)')),
                ('seasonal_dates', models.JSONField(blank=True, help_text='Optional seasonal availability', null=True)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('max_capacity', models.PositiveIntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='activity.activity')),
            ],
        ),
    ]
