# Generated by Django 5.0.1 on 2024-11-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activitybooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='itinerary',
            field=models.JSONField(default=list, help_text='List of itinerary items'),
        ),
    ]
