# Generated by Django 5.0.1 on 2024-10-30 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, help_text='Number of days for the tour', validators=[django.core.validators.MinValueValidator(1, message='Duration must be at least 1 day'), django.core.validators.MaxValueValidator(30, message='Duration cannot exceed 30 days')]),
        ),
    ]
